# Generated by Django 3.2.5 on 2022-02-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hksfbclone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_groups',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
