# Generated by Django 3.2.5 on 2021-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hksfbclone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_details',
            name='imgp',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='imgs'),
        ),
    ]
