# Generated by Django 3.2.5 on 2022-02-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hksfbclone', '0002_chat_groups_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_groups',
            name='user',
            field=models.ManyToManyField(to='hksfbclone.profile_details'),
        ),
    ]
