# Generated by Django 3.2.5 on 2022-02-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hksfbclone', '0003_alter_chat_groups_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_groups',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
