# Generated by Django 3.2.5 on 2022-02-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hksfbclone', '0004_chat_groups_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from_pro', to='hksfbclone.profile_details')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='hksfbclone.chat_groups')),
                ('to_user', models.ManyToManyField(related_name='to_pro', to='hksfbclone.profile_details')),
            ],
        ),
    ]
