# Generated by Django 3.2.5 on 2022-02-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hksfbclone', '0005_group_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_request',
            old_name='from_user',
            new_name='from_pro',
        ),
        migrations.RenameField(
            model_name='group_request',
            old_name='to_user',
            new_name='to_pro',
        ),
    ]
